apiVersion: v1
kind: Pod
metadata:
  name: pod3
spec:
  containers:
  - name: nginx
    image: nginx:1.21.1
    ports:
    - name: nginx
      containerPort: 3000
  - name: collectlog
    image: afakharany/watcher:latest
  - name: alpine
    image: alpine:3.14
